# Generated by Django 6.0.4 on 2026-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="business_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="provider",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
