# Generated by Django 6.0.4 on 2026-05-30 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_client_user_alter_provider_user"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_interval_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[(15, "15 minut"), (30, "30 minut"), (60, "1 godzina")],
                        default=30,
                    ),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.provider",
                    ),
                ),
            ],
        ),
    ]
